#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR


./node_modules/coffee-script/bin/coffee -o lib -c src && \
doctoc README.md && \
echo "![](https://github.com/loveencounterflow/FLOWMATIC/raw/master/artwork/flowmatic-logo-4a.png)"|cat - README.md > /tmp/flowmatic-README.tmp && mv /tmp/flowmatic-README.tmp README.md && \
# coffeedoc -o doc src && \
git add --all && \
git commit -m "autocommit"
git push -u origin master
echo
