// Generated by CoffeeScript 1.12.6
(function() {
  var $, CND, CS, PS, alert, badge, debug, echo, help, info, log, map, rpr, urge, warn, whisper;

  CND = require('cnd');

  rpr = CND.rpr.bind(CND);

  badge = 'DEMO-COFFEE-LEX';

  log = CND.get_logger('plain', badge);

  info = CND.get_logger('info', badge);

  whisper = CND.get_logger('whisper', badge);

  alert = CND.get_logger('alert', badge);

  debug = CND.get_logger('debug', badge);

  warn = CND.get_logger('warn', badge);

  help = CND.get_logger('help', badge);

  urge = CND.get_logger('urge', badge);

  echo = CND.echo.bind(CND);

  PS = require('pipestreams');

  $ = PS.$, map = PS.map;

  CS = require('coffeescript');

  this.U = require('./utilities');

  this.LEXER = require('./lexer');

  this.PROTOCOL = require('./protocol');

  this.ARABIKA = require('./basic-arabika');

}).call(this);

//# sourceMappingURL=main.js.map
