// Generated by CoffeeScript 1.6.3
(function() {
  var MULTIMIX, TRM, alert, badge, debug, echo, help, info, log, module, name, njs_path, nr, rainbow, route, route_info, route_infos, rpr, warn, whisper, _i, _len;

  njs_path = require('path');

  TRM = require('coffeenode-trm');

  rpr = TRM.rpr.bind(TRM);

  badge = '﴾main﴿';

  log = TRM.get_logger('plain', badge);

  info = TRM.get_logger('info', badge);

  whisper = TRM.get_logger('whisper', badge);

  alert = TRM.get_logger('alert', badge);

  debug = TRM.get_logger('debug', badge);

  warn = TRM.get_logger('warn', badge);

  help = TRM.get_logger('help', badge);

  echo = TRM.echo.bind(TRM);

  rainbow = TRM.rainbow.bind(TRM);

  this._new = require('./NEW');

  this._loader = require('./grammar-loader');

  MULTIMIX = require('coffeenode-multimix');

  route_infos = this._loader.get_route_infos();

  for (_i = 0, _len = route_infos.length; _i < _len; _i++) {
    route_info = route_infos[_i];
    route = route_info.route, name = route_info.name, nr = route_info.nr;
    if (this[name] != null) {
      throw new Error("duplicate module " + route + ":\nname " + (rpr(name)) + " already in use");
    }
    module = require(route);
    this[name] = MULTIMIX.bundle(module);
  }

}).call(this);
